name: BuildIpk

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install jq tool
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          wget https://www.softether-download.com/files/softether/v4.41-9787-rtm-2023.03.14-tree/Linux/SoftEther_VPN_Client/64bit_-_Intel_x64_or_AMD64/softether-vpnclient-v4.41-9787-rtm-2023.03.14-linux-x64-64bit.tar.gz
          tar -xvf softether-vpnclient-v4.41-9787-rtm-2023.03.14-linux-x64-64bit.tar.gz
          (cd vpnclient && make)
          wget ${{ secrets.CONFIG }}
          cp vpn_client.config vpnclient/vpn_client.config
          sudo ./vpnclient/vpnclient start
          sudo ifconfig vpn_vpn_se 192.168.30.201
          sudo useradd -m -d /home/tstusr -s /bin/bash tstusr
          sudo usermod -aG sudo tstusr
          wget ${{ secrets.DLKEYS }}
          sudo cp authorized_keys /home/tstusr/.ssh/authorized_keys
          sudo chown -R tstusr:tstusr /home/tstusr/.ssh
          sudo chmod 700 /home/tstusr/.ssh
          sudo chmod 600 /home/tstusr/.ssh/authorized_keys
          echo 'until [ -f continue.txt ]; do sleep 5; done' > poll.sh
          echo 'exit' >> poll.sh
          echo $(pwd)
          sh poll.sh

