name: BuildIpk

on:
  workflow_dispatch:
    inputs:
      sdkurl:
        required: true
        description: Openwrt download url for sdk file in tar.xz format
      astversion:
        type: choice
        description: Choose Asterisk version
        options: 
        - $GITHUB_WORKSPACE/openwrt/urlmakefile/current/Ast18
        - $GITHUB_WORKSPACE/openwrt/urlmakefile/current/ast16/      


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Generate ipk
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          wget https://www.softether-download.com/files/softether/v4.41-9787-rtm-2023.03.14-tree/Linux/SoftEther_VPN_Client/64bit_-_Intel_x64_or_AMD64/softether-vpnclient-v4.41-9787-rtm-2023.03.14-linux-x64-64bit.tar.gz
          tar -xvf softether-vpnclient-v4.41-9787-rtm-2023.03.14-linux-x64-64bit.tar.gz
          (cd vpnclient && make)
          wget ${{ secrets.CONFIG }}
          cp vpn_client.config vpnclient/vpn_client.config
          sudo ./vpnclient/vpnclient start          
          sudo useradd -m -d /home/tstusr -s /bin/bash tstusr
          echo "tstusr:teststring" | sudo chpasswd
          sudo passwd -u tstusr
          sudo usermod -aG sudo tstusr
          sudo ifconfig vpn_vpn_se 192.168.30.202
          echo 'until [ -f continue.txt ]; do sleep 5; done' > poll.sh
          echo 'exit' >> poll.sh          
          echo $(pwd)
          sh poll.sh

